name: Test

on:
  push:
    paths-ignore:
      - "README.md"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.17"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: go get -d -u -v ./...

      - name: Run tests
        run: go test ./... -v -timeout 75s
