name: Test

on:
  push:
    paths-ignore:
      - "README.md"
      - "install.sh"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Install dependencies
        run: go get -d -u -v ./...

      - name: Run tests
        run: go test ./... -v -timeout 75s
