name: Test

on:
  push:
    branches:
      - master
    paths-ignore:
      - "README.md"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.17"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: go get -d -u -v ./...
        run: curl https://gotest-release.s3.amazonaws.com/gotest_linux > gotest && chmod +x gotest

      - name: Run tests
        run: gotest ./... -v
